### ISSUE TITLE
运行以后，一段时间停止，这个表示什么意思

### ISSUE THREAD

**Issue by shenqimolisha** [zhonghaibin/rar#1]
![image](https://user-images.githubusercontent.com/93420332/170670678-bbf295e3-9ae3-441e-8eb4-e1d51ce9cc44.png)
请问这个代表什么意思。运行后pass.txt由8000k增长到20000k内存，这个该如何查找密码？

**Comment by zhonghaibin** [comment]
放弃吧，破解不了。rar解压软件本身自带有限制尝试解压密码次数。达到最大的尝试次数再调用rar也不执行了。
